name: deploy_to_cocoapods

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          LIB_VERSION=${TAG#v}
          echo "LIB_VERSION=${LIB_VERSION}"
          pod lib lint --allow-warnings
          pod trunk push NISdk.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
